### ISSUE TITLE
demo_spatiotemporal_det_onnx.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2374] opened 2023-04-11 08:19 UTC
### The doc issue

demo_spatiotemporal_det_onnx.py script made an error below.

```
$ python3 demo/demo_spatiotemporal_det_onnx.py demo/demo.mp4 demo/demo_spatiotemporal_det.mp4 --config configs/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py --onnx-file slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.onnx --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --action-score-thr 0.5 --label-map tools/data/ava/label_map.txt --predict-stepsize 8 --output-stepsize 4 --output-fps 6
python3: can't open file 'demo/demo_spatiotemporal_det_onnx.py': [Errno 2] No such file or directory
```

Please tell me the solution.

**Comment by hukkai** [comment] 2023-04-14 02:25
The error is stated as shown in the error log. Your command cannot find this file: `demo/demo_spatiotemporal_det_onnx.py`, which means you are in the wrong directory

**Comment by cir7** [comment] 2023-04-14 03:11
This is not a bug, we will close the issue, feel free to reopen it if you have any further questions.

**Closed by cir7** 2023-04-14 03:11 UTC
