### ISSUE TITLE
There is a bug for tensorboard code

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmaction2#469] opened 2020-12-21 05:26 UTC
my enviroment:
```
mmaction2--0.8.0
mmcv-full--1.1.6
pytorch--1.6.0
```

the tensorboard result is here... It seems like the value of the abscissa is wrong, which result in this mistake. Sorry about cannot debug due to I'm running the code and cannot stop it.

![image](https://user-images.githubusercontent.com/73068772/102741983-c2599580-438e-11eb-8c88-5b224e084742.png)

**Comment by congee524** [comment] 2020-12-21 09:52
Could you tell me which config file do you use? (or simply how you train the model)

**Comment by mitming** [comment] 2020-12-21 10:01
slowfast, sorry that i am not in my lab now, so i cannot tell you the whole config



---Original---

**Comment by mitming** [comment] 2020-12-21 10:55
@congee524 thanks your patience, here is my [config](https://github.com/open-mmlab/mmaction2/files/5723913/slowfast_r50_24x1x1_100e_sthv1_rgb.txt)

**Comment by congee524** [comment] 2020-12-21 12:06
Maybe this is an issue of Tensorboard.
Try to restart Tensorboard, and wait for a moment.

Could you provide the tensorboard log file?

**Comment by mitming** [comment] 2020-12-21 12:07
> Maybe this is an issue of Tensorboard.
> Try to restart Tensorboard, and wait for a moment.
> 
> Could you provide the tensorboard log file?

sorry I just remove the tensorboard log file, I will reproduce that and reply to you soon

**Comment by mitming** [comment] 2020-12-21 14:11
hi @congee524 , I tried restart tensorboard and wait for a while, but this problem is still here, could you please try it? Here is my [tensorboard log file](https://github.com/open-mmlab/mmaction2/files/5724717/events.out.tfevents.1608552619.liuhong-mac-All-Series.18060.zip)

**Comment by mitming** [comment] 2020-12-27 04:58
hi @dreamerlin @congee524 , have you reproduced this bug ?

**Comment by congee524** [comment] 2020-12-27 06:37
hi, I used your log file and didn't encounter this problem

**Comment by congee524** [comment] 2020-12-27 06:37
Did you set the `Horizontal Axis` as `RELATIVE`?

**Comment by mitming** [comment] 2020-12-27 06:49
> Did you set the `Horizontal Axis` as `RELATIVE`?

When I set the `Horizontal Axis` as `RELATIVE`, there are still something look bad, specifically, the `Horizontal Axis` is not iteration or epoch, and the `Vertical Axis` will show a straight line like this:

![image](https://user-images.githubusercontent.com/73068772/103165418-8d4bb800-4852-11eb-88ed-06fb5e0c7255.png)

How can I set the value of  `Horizontal Axis` as iteration or epoch nums?

**Comment by congee524** [comment] 2020-12-27 07:07
The abscissa of relative is the training time, there is validation between two trainning epoch. I wanna know whether there is something wrong with step or time

**Comment by congee524** [comment] 2020-12-27 07:09
maybe the iter was setted as _inner_iter incorrectyle. I will try to reproduce it.

**Comment by mitming** [comment] 2020-12-27 07:12
> The abscissa of relative is the training time, there is validation between two trainning epoch. I wanna know whether there is something wrong with step or time

There is no error about accuracy or step, but it is strange that validate abscissa is epoch but training abscissa is iteration, for user I think a union style is more helpful. Hope you can reproduce it and fix it

**Comment by congee524** [comment] 2020-12-28 09:59
hi, I used your config file but cannot reproduce the problem. 
Have you changed any other code? Especially the code in the folders `mmaction/apis core utils`

**Comment by mitming** [comment] 2020-12-28 10:52
> hi, I used your config file but cannot reproduce the problem.
> Have you changed any other code? Especially the code in the folders `mmaction/apis core utils`

Sorry I don't change any code, here is my enviroment:
```
mmaction2 -- 0.9.0
mmcv-full -- 1.1.6
pytorch -- 1.6.0
```

and the output info:
```
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMAction2: 0.9.0+fef4aee
```

**Comment by congee524** [comment] 2020-12-28 12:58
There is a bug in mmcv 1.1.6 in fact and it has been fixed in the latest version. You can upgrade mmcv to 1.2.3

**Closed** 2020-12-28 12:58 UTC
Labels: need reproduce

**Comment by mitming** [comment] 2020-12-28 12:59
> There is a bug in mmcv 1.1.6 in fact and it has been fixed in the latest version. You can upgrade mmcv to 1.2.3

Thansk a lot
