### ISSUE TITLE
load_from

### ISSUE THREAD

**Issue by xiangwentao666** [open-mmlab/mmaction2#1582] opened 2022-04-14 11:56 UTC
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by kennymckormick** [comment] 2022-04-15 01:57
Duplicate of #1583. Closed

**Closed by kennymckormick** 2022-04-15 01:57 UTC
